version: '3.0'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: amazon
      POSTGRES_PASSWORD: amazon
      POSTGRES_DB: amazon
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
